name: Deploy blog

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build container image
        run:  docker build --build-arg NOTION_API_KEY=${{ secrets.NOTION_API_KEY }} --build-arg NOTION_BLOG_DATABASE_ID=${{ secrets.NOTION_BLOG_DATABASE_ID }} -t registry.digitalocean.com/software-crafter-nextjs-blog/blog:latest .

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
            version: 1.92.0
            token: ${{ secrets.DIGITALOCEAN_REGISTRY_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/software-crafter-nextjs-blog/blog:latest

#      - name: Setup Node.js environment
#        uses: actions/setup-node@v2
#        with:
#          node-version: '18' # puedes usar cualquier versión de Node.js que necesites
#
#      - name: Cache Node.js modules
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
#
#      - name: Install Dependencies
#        run: npm ci
#
#      - name: Run Linter
#        run: npm run lint

#      - name: Run Tests
#        run: npm run test

#      - name: Build Project
#        run: npm run build


#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: registry.digitalocean.com/software-crafter-nextjs-blog/blog:latest

#      - name: DigitalOcean Deploy
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#
#      - run: doctl apps create --spec .do/app.yaml
